set t_Co=256
syntax on

execute pathogen#infect()

set tabstop=4
set undodir=path/to/dir

let g:Powerline_symbols='fancy'

"autocmd vimenter * NERDTree

autocmd bufenter * if(winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

filetype plugin on
